[source]
name = "gitleaks config"
description = "Gitleaks configuration for detecting secrets"

[source.git]
max_depth = 0

[[rules]]
id = "entropy"
description = "Base64 High Entropy Strings"
regex = '''(?i)(?:password|secret|api[_-]?key|token|auth) = ['\"]?([A-Za-z0-9+/=]{20,})['\"]?'''
entropy = 4.5
keywords = ["password", "secret", "api_key", "token", "auth"]
